CREATE DATABASE Chocolate_Sales;

CREATE TABLE ChocolateSales (
    Sales_Person VARCHAR(100) NOT NULL,
    Country VARCHAR(50) NOT NULL,
    Product VARCHAR(100) NOT NULL,
    DATE DATETIME NOT NULL,
    Amount DECIMAL(12, 4) NOT NULL, -- Initially imported as string to handle '$'
    Boxes_Shipped INT
);

SELECT * FROM ChocolateSales;

###QUESTIONS###

# Show all sales made in 'India' where the 'Amount' is greater than 5,000.
SELECT * FROM ChocolateSales 
WHERE Country = 'India' AND Amount > 5000;

# List the top 10 largest sales (by Amount) including the Sales Person and Product.
SELECT  Sales_Person as "Sales Person", Product, Amount
FROM ChocolateSales
ORDER BY Amount DESC 
LIMIT 10;

# How many transactions did each country record?
SELECT Country as "Country" , COUNT(Amount) AS Transaction_Count
FROM ChocolateSales 
GROUP BY Country;

# What is the total revenue (Amount) generated by each Sales Person?
SELECT Sales_Person, SUM(Amount) AS Total_Revenue
FROM ChocolateSales 
GROUP BY Sales_Person
ORDER BY Total_Revenue DESC;

# What is the average number of boxes shipped per product?
SELECT Product, AVG(Boxes_Shipped) AS "Avg Boxes Shipped"
FROM ChocolateSales
GROUP BY Product;

# Find all products that have the word 'Choco' in their name.
SELECT DISTINCT Product 
FROM ChocolateSales 
WHERE Product LIKE '%Choco%';

# Find all sales that are above the overall average sale amount.
SELECT * FROM ChocolateSales 
WHERE Amount > (SELECT AVG(Amount) FROM ChocolateSales);

# Categorize sales as 'Large' (Amount > 10k), 'Medium' (5k-10k), or 'Small' (<5k).
SELECT Product, Amount,
  CASE 
    WHEN Amount > 10000 THEN 'Large'
    WHEN Amount BETWEEN 5000 AND 10000 THEN 'Medium'
    ELSE 'Small'
  END AS Sale_Size
FROM ChocolateSales;

### GOOD BYE! ###